services:
  db:
    image: mysql:9
    volumes:
      - db_data:/var/lib/mysql
      - ./dev/mysql/db/:/db/
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    ports:
      - '${PROJECTPORTPREFIX}03:3306'
  app:
    #image: wordpress:latest
    build:
      context: dev/app
      dockerfile: Dockerfile
    volumes:
      - './dev/app/php.ini:/usr/local/etc/php/php.ini:ro'
      - ./www:/var/www/html
    ports:
      - '${PROJECTPORTPREFIX}00:80'
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
  wp_data:
